AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation

Outputs:
  SravanthiApplicationLoadBalancer:
    Value: !GetAtt SravanthiApplicationLoadBalancer.DNSName

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: sravanthi-cloudformation-bucket
  MyQueue:
    Type: AWS::SQS::Queue
  SravanthiInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      SecurityGroupIds:
        - !Ref SravanthiInstanceSecurityGroup
      Tags:
        - Key: Name
          Value: sravanthiEc2

  SravanthiApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - subnet-0e8cecdb378d728af
        - subnet-0441c0b1c024fa494

  SravanthiInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: AllowEC2Traffic
      GroupDescription: Enable SSH and Http access on the inbound port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SravanthiInstanceSecurityGroup

Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
