AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: sravanthi-cloudformation-bucket
  MyQueue:
    Type: AWS::SQS::Queue
  SravanthiInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      Tags:
        - Key: BucketName
          Value: sravanthiEc2

Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
