AWSTemplateFormatVersion: 2010-09-09
Description: Academy Demo CloudFormation
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: sravanthi-cloudformation-bucket
  MyQueue:
    Type: AWS::SQS::Queue
